name: Prerelease

on:
  workflow_dispatch

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          git_user_signingkey: true
          git_commit_gpgsign: true
          git_push_gpgsign: false
      - uses: knope-dev/action@v1
        with:
          version: 0.16.2
      - run: knope release --prerelease-label=rc
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}