name: Publish

on:
  release:
    types: [released, prereleased]
  workflow_dispatch:

permissions: {}

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    environment: "crates.io"
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - uses: actions-rust-lang/setup-rust-toolchain@166cdcfd11aee3cb47222f9ddb555ce30ddb9659 # v1.17.0
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish --workspace
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
