name: Publish

on:
  release:
    types: [released, prereleased]
  workflow_dispatch:

permissions: {}

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    environment: "crates.io"
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions-rust-lang/setup-rust-toolchain@2b1f5e9b395427c92ee4e3331786ca3c37afe2d7 # v1.16.0
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish --workspace
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
