name: Publish

on:
  release:
    types: [released, prereleased]
  workflow_dispatch:

permissions: {}

jobs:
  publish-crate:
    runs-on: ubuntu-latest
    environment: "crates.io"
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
      - uses: actions-rust-lang/setup-rust-toolchain@46268bd060767258de96ed93c1251119784f2ab6 # v1.16.1
      - uses: rust-lang/crates-io-auth-action@v1
        id: auth
      - run: cargo publish --workspace
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
