name: Release Dry Run

on:
  push:
    branches:
      - main

jobs:
  dry-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: knope-dev/action@v2.1.0
        with:
          version: 0.17.0
      - run: knope release --dry-run
