name: Release Dry Run

on:
  push:
    branches:
      - main

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}
      - uses: Swatinem/rust-cache@v2
      - uses: knope-dev/action
        with:
          version: 0.7.3
      - run: knope release --dry-run